workflows:
  ios-build:
    name: iOS Build

    working_directory: iosproject

    environment:
      xcode: 16.4

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate iOS project
        script: |
          make bootstrap

      - name: Build iOS app
        script: |
          xcodebuild \
            -project *.xcodeproj \
            -scheme "JournalCollage" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

    artifacts:
      - "iosproject/**/*.app"
