export type ProductLocale = 'en' | 'zh-Hans';

const copy = {
  en: {
    'tab.create': 'Create',
    'tab.assets': 'Assets',
    'tab.mine': 'Mine',
    'create.title': 'New collage',
    'create.start': 'Start a new collage',
    'create.placeholder': 'Your creation space is being prepared.',
    'create.addPhoto': 'Add photo',
    'create.blankCanvas': 'Start with a blank canvas',
    'create.materialPack': 'Start with a material pack',
    'create.recentDrafts': 'Recent creations',
    'create.tearPaper': 'Tear paper, your way',
    'create.texture': 'Add grain, set the mood',
    'editor.export': 'Export',
    'editor.tool.image': 'Photo',
    'editor.tool.material': 'Material',
    'editor.tool.background': 'Background',
    'editor.tool.text': 'Text',
    'editor.tool.scissors': 'Scissors',
    'editor.tool.emboss': 'Emboss',
    'editor.tool.brush': 'Brush',
    'editor.text.title': 'Text',
    'editor.text.cancel': 'Cancel',
    'editor.text.done': 'Done',
    'editor.text.placeholder': 'Write something',
    'editor.text.size': 'Size',
    'editor.text.align': 'Align',
    'editor.text.opacity': 'Opacity',
    'editor.text.edit': 'Edit text',
    'editor.text.none': 'None',
    'editor.text.ink': 'Ink',
    'editor.text.paper': 'Paper',
    'editor.text.pink': 'Pink',
    'editor.text.font': 'Font',
    'editor.text.variant': 'Style',
    'editor.text.color': 'Color',
    'editor.text.background': 'Background',
    'editor.text.left': 'Left',
    'editor.text.center': 'Center',
    'editor.text.right': 'Right',
    'editor.text.white': 'White',
    'editor.text.tape': 'Tape',
    'editor.source.library': 'Choose from Library',
    'editor.source.camera': 'Take Photo',
    'editor.source.collage': 'Collage layout',
    'editor.source.cancel': 'Cancel',
    'editor.layer.selected': 'Selected layer',
    'editor.layer.up': 'Forward',
    'editor.layer.down': 'Backward',
    'editor.layer.copy': 'Duplicate',
    'editor.layer.delete': 'Delete',
    'editor.layer.crop': 'Crop',
    'editor.layer.shadow': 'Shadow',
    'editor.layer.opacity': 'Opacity',
    'editor.layer.corner': 'Corners',
    'editor.layer.outline': 'Outline',
    'editor.layer.effects': 'Effects',
    'editor.layer.scissors': 'Scissors',
    'editor.layer.emboss': 'Emboss',
    'editor.cut.title': 'Straight cut',
    'editor.cut.cancel': 'Cancel',
    'editor.cut.done': 'Done',
    'editor.cut.hint': 'Drag to position; rotate with two fingers. Both pieces remain editable.',
    'editor.cut.rotate': 'Rotate 15°',
    'editor.cut.unavailableTitle': 'Select an image',
    'editor.cut.unavailableBody': 'Straight cut is available for image layers.',
    'editor.cut.lockedTitle': 'Layer locked',
    'editor.cut.lockedBody': 'Unlock this image before cutting it.',
    'editor.cut.straight': 'Straight cut',
    'editor.cut.wave': 'Scallop cut',
    'editor.cut.free': 'Brush cut',
    'editor.cut.subject': 'Subject cut',
    'editor.cut.comingSoonTitle': 'Coming soon',
    'editor.cut.comingSoonBody': 'This cut method is next in the editor roadmap.',
    'editor.cut.selectHint': 'Select an image layer to start cutting.',
    'editor.cut.dismiss': 'Dismiss cut options',
  },
  'zh-Hans': {
    'tab.create': '创作',
    'tab.assets': '素材',
    'tab.mine': '我的',
    'create.title': '新拼贴',
    'create.start': '开始新拼贴',
    'create.placeholder': '创作首页正在准备中。',
    'create.addPhoto': '添加照片',
    'create.blankCanvas': '从空白画布开始',
    'create.materialPack': '从素材包开始',
    'create.recentDrafts': '最近创作',
    'create.tearPaper': '限时体验创意撕纸',
    'create.texture': '颗粒一加，氛围到位',
    'editor.export': '导出',
    'editor.tool.image': '图片',
    'editor.tool.material': '素材',
    'editor.tool.background': '背景',
    'editor.tool.text': '文字',
    'editor.tool.scissors': '剪刀',
    'editor.tool.emboss': '压花',
    'editor.tool.brush': '画笔',
    'editor.text.title': '文字',
    'editor.text.cancel': '取消',
    'editor.text.done': '完成',
    'editor.text.placeholder': '写点什么',
    'editor.text.size': '大小',
    'editor.text.align': '对齐',
    'editor.text.opacity': '透明度',
    'editor.text.edit': '编辑文字',
    'editor.text.none': '无',
    'editor.text.ink': '黑',
    'editor.text.paper': '纸张',
    'editor.text.pink': '粉',
    'editor.text.font': '字体',
    'editor.text.variant': '样式',
    'editor.text.color': '颜色',
    'editor.text.background': '底色',
    'editor.text.left': '左对齐',
    'editor.text.center': '居中',
    'editor.text.right': '右对齐',
    'editor.text.white': '白底',
    'editor.text.tape': '胶带',
    'editor.source.library': '从相册选择图片',
    'editor.source.camera': '拍照',
    'editor.source.collage': '拼图布局',
    'editor.source.cancel': '取消',
    'editor.layer.selected': '已选中图层',
    'editor.layer.up': '上移',
    'editor.layer.down': '下移',
    'editor.layer.copy': '复制',
    'editor.layer.delete': '删除',
    'editor.layer.crop': '裁切',
    'editor.layer.shadow': '阴影',
    'editor.layer.opacity': '透明度',
    'editor.layer.corner': '圆角',
    'editor.layer.outline': '描边',
    'editor.layer.effects': '效果',
    'editor.layer.scissors': '剪刀',
    'editor.layer.emboss': '压花',
    'editor.cut.title': '直线剪',
    'editor.cut.cancel': '取消',
    'editor.cut.done': '完成',
    'editor.cut.hint': '拖动调整位置，双指旋转调整角度；剪开的两片都可以继续编辑。',
    'editor.cut.rotate': '旋转 15°',
    'editor.cut.unavailableTitle': '请选择图片',
    'editor.cut.unavailableBody': '直线剪目前仅支持图片图层。',
    'editor.cut.lockedTitle': '图层已锁定',
    'editor.cut.lockedBody': '请先解锁图片，再进行剪切。',
    'editor.cut.straight': '直线剪',
    'editor.cut.wave': '花边剪',
    'editor.cut.free': '涂抹剪',
    'editor.cut.subject': '主体剪',
    'editor.cut.comingSoonTitle': '即将支持',
    'editor.cut.comingSoonBody': '该剪刀功能将作为下一步编辑能力提供。',
    'editor.cut.selectHint': '请先在画布上选择图片图层。',
    'editor.cut.dismiss': '收起剪刀选项',
  },
} as const;

export type ProductCopyKey = keyof (typeof copy)['en'];

/** A missing product string is a development error, never visible fallback UI. */
export const t = (locale: ProductLocale, key: ProductCopyKey): string => copy[locale][key] ?? copy.en[key];

export const resolveProductLocale = (deviceLocale = Intl.DateTimeFormat().resolvedOptions().locale): ProductLocale =>
  deviceLocale.toLowerCase().startsWith('zh') ? 'zh-Hans' : 'en';
