export type ProductLocale = 'en' | 'zh-Hans';

const copy = {
  en: {
    'tab.create': 'Create',
    'tab.assets': 'Assets',
    'tab.mine': 'Mine',
    'create.title': 'New collage',
    'create.start': 'Start a new collage',
    'create.placeholder': 'Your creation space is being prepared.',
    'create.addPhoto': 'Add photo',
    'create.blankCanvas': 'Start with a blank canvas',
    'create.materialPack': 'Start with a material pack',
    'create.recentDrafts': 'Recent creations',
    'create.tearPaper': 'Tear paper, your way',
    'create.texture': 'Add grain, set the mood',
    'editor.export': 'Export',
    'editor.tool.image': 'Photo',
    'editor.tool.material': 'Material',
    'editor.tool.background': 'Background',
    'editor.tool.text': 'Text',
    'editor.tool.scissors': 'Scissors',
    'editor.tool.emboss': 'Emboss',
    'editor.tool.brush': 'Brush',
    'editor.source.library': 'Choose from Library',
    'editor.source.camera': 'Take Photo',
    'editor.source.collage': 'Collage layout',
    'editor.source.cancel': 'Cancel',
    'editor.layer.selected': 'Selected layer',
    'editor.layer.up': 'Forward',
    'editor.layer.down': 'Backward',
    'editor.layer.copy': 'Duplicate',
    'editor.layer.delete': 'Delete',
    'editor.layer.crop': 'Crop',
    'editor.layer.shadow': 'Shadow',
    'editor.layer.opacity': 'Opacity',
    'editor.layer.corner': 'Corners',
    'editor.layer.outline': 'Outline',
    'editor.layer.effects': 'Effects',
    'editor.layer.scissors': 'Scissors',
    'editor.layer.emboss': 'Emboss',
  },
  'zh-Hans': {
    'tab.create': '创作',
    'tab.assets': '素材',
    'tab.mine': '我的',
    'create.title': '新拼贴',
    'create.start': '开始新拼贴',
    'create.placeholder': '创作首页正在准备中。',
    'create.addPhoto': '添加照片',
    'create.blankCanvas': '从空白画布开始',
    'create.materialPack': '从素材包开始',
    'create.recentDrafts': '最近创作',
    'create.tearPaper': '限时体验创意撕纸',
    'create.texture': '颗粒一加，氛围到位',
    'editor.export': '导出',
    'editor.tool.image': '图片',
    'editor.tool.material': '素材',
    'editor.tool.background': '背景',
    'editor.tool.text': '文字',
    'editor.tool.scissors': '剪刀',
    'editor.tool.emboss': '压花',
    'editor.tool.brush': '画笔',
    'editor.source.library': '从相册选择图片',
    'editor.source.camera': '拍照',
    'editor.source.collage': '拼图布局',
    'editor.source.cancel': '取消',
    'editor.layer.selected': '已选中图层',
    'editor.layer.up': '上移',
    'editor.layer.down': '下移',
    'editor.layer.copy': '复制',
    'editor.layer.delete': '删除',
    'editor.layer.crop': '裁切',
    'editor.layer.shadow': '阴影',
    'editor.layer.opacity': '透明度',
    'editor.layer.corner': '圆角',
    'editor.layer.outline': '描边',
    'editor.layer.effects': '效果',
    'editor.layer.scissors': '剪刀',
    'editor.layer.emboss': '压花',
  },
} as const;

export type ProductCopyKey = keyof (typeof copy)['en'];

/** A missing product string is a development error, never visible fallback UI. */
export const t = (locale: ProductLocale, key: ProductCopyKey): string => copy[locale][key] ?? copy.en[key];

export const resolveProductLocale = (deviceLocale = Intl.DateTimeFormat().resolvedOptions().locale): ProductLocale =>
  deviceLocale.toLowerCase().startsWith('zh') ? 'zh-Hans' : 'en';
