export type ProductLocale = 'en' | 'zh-Hans';

const copy = {
  en: {
    'tab.create': 'Create',
    'tab.assets': 'Assets',
    'tab.mine': 'Mine',
    'create.title': 'New collage',
    'create.start': 'Start a new collage',
    'create.placeholder': 'Your creation space is being prepared.',
    'create.addPhoto': 'Add photo',
    'create.blankCanvas': 'Start with a blank canvas',
    'create.materialPack': 'Start with a material pack',
    'create.recentDrafts': 'Recent creations',
    'create.tearPaper': 'Tear paper, your way',
    'create.texture': 'Add grain, set the mood',
    'editor.export': 'Export',
    'editor.feedback.finishBrush': 'Finish or cancel the brush edit first',
    'editor.tool.image': 'Photo',
    'editor.tool.material': 'Material',
    'editor.tool.background': 'Background',
    'editor.tool.text': 'Text',
    'editor.tool.scissors': 'Scissors',
    'editor.tool.emboss': 'Emboss',
    'editor.tool.brush': 'Brush',
    'editor.brush.title': 'Brush',
    'editor.brush.undo': 'Undo stroke',
    'editor.brush.redo': 'Redo stroke',
    'editor.brush.clear': 'Clear',
    'editor.brush.eraser': 'Eraser',
    'editor.brush.kind': 'Brush',
    'editor.brush.color': 'Color',
    'editor.brush.size': 'Size',
    'editor.brush.edit': 'Edit',
    'editor.brush.plain': 'Plain',
    'editor.brush.crayon': 'Crayon',
    'editor.brush.marker': 'Marker',
    'editor.brush.stitch': 'Stitch',
    'editor.brush.knit': 'Knit',
    'editor.brush.beads': 'Beads',
    'editor.brush.lace': 'Lace',
    'editor.brush.bow': 'Bow',
    'editor.text.title': 'Text',
    'editor.text.cancel': 'Cancel',
    'editor.text.done': 'Done',
    'editor.text.placeholder': 'Write something',
    'editor.text.size': 'Size',
    'editor.text.align': 'Align',
    'editor.text.opacity': 'Opacity',
    'editor.text.edit': 'Edit text',
    'editor.text.none': 'None',
    'editor.text.ink': 'Ink',
    'editor.text.paper': 'Paper',
    'editor.text.pink': 'Pink',
    'editor.text.font': 'Font',
    'editor.text.variant': 'Style',
    'editor.text.color': 'Color',
    'editor.text.background': 'Background',
    'editor.text.left': 'Left',
    'editor.text.center': 'Center',
    'editor.text.right': 'Right',
    'editor.text.white': 'White',
    'editor.text.tape': 'Tape',
    'editor.source.library': 'Choose from Library',
    'editor.source.camera': 'Take Photo',
    'editor.source.collage': 'Collage layout',
    'editor.source.cancel': 'Cancel',
    'editor.layer.selected': 'Selected layer',
    'editor.layer.up': 'Forward',
    'editor.layer.down': 'Backward',
    'editor.layer.copy': 'Duplicate',
    'editor.layer.delete': 'Delete',
    'editor.layer.crop': 'Crop',
    'editor.layer.shadow': 'Shadow',
    'editor.layer.opacity': 'Opacity',
    'editor.layer.corner': 'Corners',
    'editor.layer.outline': 'Outline',
    'editor.layer.effects': 'Effects',
    'editor.layer.scissors': 'Scissors',
    'editor.layer.emboss': 'Emboss',
    'editor.effects.title': 'Effects',
    'editor.effects.cancel': 'Cancel',
    'editor.effects.done': 'Done',
    'editor.effects.remove': 'Remove',
    'editor.effects.structure': 'Structure',
    'editor.effects.texture': 'Texture',
    'editor.effects.none': 'None',
    'editor.effects.presets': 'Presets',
    'editor.effects.presetPaper': 'Torn paper',
    'editor.effects.presetPrint': 'Soft grain',
    'editor.effects.shadow': 'Shadow',
    'editor.effects.outline': 'Outline',
    'editor.effects.torn': 'Torn edge',
    'editor.effects.grain': 'Paper grain',
    'editor.effects.blur': 'Blur',
    'editor.effects.width': 'Width',
    'editor.effects.intensity': 'Intensity',
    'editor.effects.radius': 'Radius',
    'editor.effects.scale': 'Scale',
    'editor.effects.corners': 'Corners',
    'editor.effects.tape': 'Attached',
    'editor.effects.float': 'Floating',
    'editor.effects.lace': 'Lace frame',
    'editor.effects.back': 'Back',
    'editor.effects.previewHint': 'Preview changes are not saved until you finish effects.',
    'editor.cut.title': 'Straight cut',
    'editor.cut.cancel': 'Cancel',
    'editor.cut.done': 'Done',
    'editor.cut.hint': 'Drag to position; rotate with two fingers. Both pieces remain editable.',
    'editor.cut.rotate': 'Rotate 15°',
    'editor.cut.unavailableTitle': 'Select an image',
    'editor.cut.unavailableBody': 'Straight cut is available for image layers.',
    'editor.cut.lockedTitle': 'Layer locked',
    'editor.cut.lockedBody': 'Unlock this image before cutting it.',
    'editor.cut.straight': 'Straight cut',
    'editor.cut.wave': 'Scallop cut',
    'editor.cut.free': 'Brush cut',
    'editor.cut.subject': 'Subject cut',
    'editor.cut.comingSoonTitle': 'Coming soon',
    'editor.cut.comingSoonBody': 'This cut method is next in the editor roadmap.',
    'editor.cut.selectHint': 'Select an image layer to start cutting.',
    'editor.cut.dismiss': 'Dismiss cut options',
    'editor.cut.clear': 'Clear strokes',
    'editor.cut.hollow': 'Hollow original',
    'editor.emboss.title': 'Emboss',
    'editor.emboss.done': 'Done',
    'editor.emboss.reset': 'Reset mask',
    'editor.emboss.ratio': 'Lock ratio',
    'editor.emboss.width': 'Width',
    'editor.emboss.height': 'Height',
    'editor.emboss.unavailableTitle': 'Select an image',
    'editor.emboss.unavailableBody': 'Emboss is available for image layers.',
    'editor.emboss.selectHint': 'Select an image layer to start embossing.',
  },
  'zh-Hans': {
    'tab.create': '创作',
    'tab.assets': '素材',
    'tab.mine': '我的',
    'create.title': '新拼贴',
    'create.start': '开始新拼贴',
    'create.placeholder': '创作首页正在准备中。',
    'create.addPhoto': '添加照片',
    'create.blankCanvas': '从空白画布开始',
    'create.materialPack': '从素材包开始',
    'create.recentDrafts': '最近创作',
    'create.tearPaper': '限时体验创意撕纸',
    'create.texture': '颗粒一加，氛围到位',
    'editor.export': '导出',
    'editor.feedback.finishBrush': '请先完成或取消笔刷编辑',
    'editor.tool.image': '图片',
    'editor.tool.material': '素材',
    'editor.tool.background': '背景',
    'editor.tool.text': '文字',
    'editor.tool.scissors': '剪刀',
    'editor.tool.emboss': '压花',
    'editor.tool.brush': '画笔',
    'editor.brush.title': '画笔',
    'editor.brush.undo': '撤销一笔',
    'editor.brush.redo': '重做一笔',
    'editor.brush.clear': '清空',
    'editor.brush.eraser': '橡皮擦',
    'editor.brush.kind': '笔刷',
    'editor.brush.color': '颜色',
    'editor.brush.size': '粗细',
    'editor.brush.edit': '编辑',
    'editor.brush.plain': '普通',
    'editor.brush.crayon': '蜡笔',
    'editor.brush.marker': '马克笔',
    'editor.brush.stitch': '缝线',
    'editor.brush.knit': '针织',
    'editor.brush.beads': '珠链',
    'editor.brush.lace': '蕾丝',
    'editor.brush.bow': '蝴蝶结',
    'editor.text.title': '文字',
    'editor.text.cancel': '取消',
    'editor.text.done': '完成',
    'editor.text.placeholder': '写点什么',
    'editor.text.size': '大小',
    'editor.text.align': '对齐',
    'editor.text.opacity': '透明度',
    'editor.text.edit': '编辑文字',
    'editor.text.none': '无',
    'editor.text.ink': '黑',
    'editor.text.paper': '纸张',
    'editor.text.pink': '粉',
    'editor.text.font': '字体',
    'editor.text.variant': '样式',
    'editor.text.color': '颜色',
    'editor.text.background': '底色',
    'editor.text.left': '左对齐',
    'editor.text.center': '居中',
    'editor.text.right': '右对齐',
    'editor.text.white': '白底',
    'editor.text.tape': '胶带',
    'editor.source.library': '从相册选择图片',
    'editor.source.camera': '拍照',
    'editor.source.collage': '拼图布局',
    'editor.source.cancel': '取消',
    'editor.layer.selected': '已选中图层',
    'editor.layer.up': '上移',
    'editor.layer.down': '下移',
    'editor.layer.copy': '复制',
    'editor.layer.delete': '删除',
    'editor.layer.crop': '裁切',
    'editor.layer.shadow': '阴影',
    'editor.layer.opacity': '透明度',
    'editor.layer.corner': '圆角',
    'editor.layer.outline': '描边',
    'editor.layer.effects': '效果',
    'editor.layer.scissors': '剪刀',
    'editor.layer.emboss': '压花',
    'editor.effects.title': '效果',
    'editor.effects.cancel': '取消',
    'editor.effects.done': '完成',
    'editor.effects.remove': '移除',
    'editor.effects.structure': '结构',
    'editor.effects.texture': '质感',
    'editor.effects.none': '无',
    'editor.effects.presets': '预设',
    'editor.effects.presetPaper': '撕纸',
    'editor.effects.presetPrint': '柔和颗粒',
    'editor.effects.shadow': '阴影',
    'editor.effects.outline': '描边',
    'editor.effects.torn': '撕边',
    'editor.effects.grain': '纸张颗粒',
    'editor.effects.blur': '模糊',
    'editor.effects.width': '宽度',
    'editor.effects.intensity': '强度',
    'editor.effects.radius': '圆角',
    'editor.effects.scale': '缩放',
    'editor.effects.corners': '圆角',
    'editor.effects.tape': '贴住',
    'editor.effects.float': '浮起',
    'editor.effects.lace': '蕾丝框裁',
    'editor.effects.back': '返回',
    'editor.effects.previewHint': '当前调整仅预览，完成效果后才会保存。',
    'editor.cut.title': '直线剪',
    'editor.cut.cancel': '取消',
    'editor.cut.done': '完成',
    'editor.cut.hint': '拖动调整位置，双指旋转调整角度；剪开的两片都可以继续编辑。',
    'editor.cut.rotate': '旋转 15°',
    'editor.cut.unavailableTitle': '请选择图片',
    'editor.cut.unavailableBody': '直线剪目前仅支持图片图层。',
    'editor.cut.lockedTitle': '图层已锁定',
    'editor.cut.lockedBody': '请先解锁图片，再进行剪切。',
    'editor.cut.straight': '直线剪',
    'editor.cut.wave': '花边剪',
    'editor.cut.free': '涂抹剪',
    'editor.cut.subject': '主体剪',
    'editor.cut.comingSoonTitle': '即将支持',
    'editor.cut.comingSoonBody': '该剪刀功能将作为下一步编辑能力提供。',
    'editor.cut.selectHint': '请先在画布上选择图片图层。',
    'editor.cut.dismiss': '收起剪刀选项',
    'editor.cut.clear': '清空涂抹',
    'editor.cut.hollow': '镂空原图',
    'editor.emboss.title': '压花',
    'editor.emboss.done': '完成',
    'editor.emboss.reset': '恢复蒙版',
    'editor.emboss.ratio': '锁定比例',
    'editor.emboss.width': '宽度',
    'editor.emboss.height': '高度',
    'editor.emboss.unavailableTitle': '请选择图片',
    'editor.emboss.unavailableBody': '压花目前仅支持图片图层。',
    'editor.emboss.selectHint': '请先在画布上选择图片图层，即可开始压花。',
  },
} as const;

export type ProductCopyKey = keyof (typeof copy)['en'];

/** A missing product string is a development error, never visible fallback UI. */
export const t = (locale: ProductLocale, key: ProductCopyKey): string => copy[locale][key] ?? copy.en[key];

export const resolveProductLocale = (deviceLocale = Intl.DateTimeFormat().resolvedOptions().locale): ProductLocale =>
  deviceLocale.toLowerCase().startsWith('zh') ? 'zh-Hans' : 'en';
