import { useEffect, useMemo, useRef, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getTextFontGroups, getTextFontVariants, type TextFont } from '@journalcollage/asset-system';
import type { TextLayer } from '@journalcollage/editor-core';
import { t, type ProductLocale } from './localization';
import { productColor } from './tokens';

type Mode = 'font' | 'variant' | 'color' | 'size' | 'align' | 'background' | 'opacity';
const colors = ['#111111', '#4A4A4A', '#9A9A9A', '#FFFFFF', '#D94A38', '#E9D28A', '#8C9A8D', '#6D9BC3', '#C9B7FF'];
const backgrounds: readonly Readonly<{ value: string | null; label: 'editor.text.none' | 'editor.text.ink' | 'editor.text.paper' | 'editor.text.white' | 'editor.text.tape' }>[] = [{ value: null, label: 'editor.text.none' }, { value: '#EFE7D8', label: 'editor.text.paper' }, { value: '#FFFFFF', label: 'editor.text.white' }, { value: '#111111', label: 'editor.text.ink' }, { value: '#E9D28A', label: 'editor.text.tape' }];
export const TEXT_EDITOR_PANEL_HEIGHT = 238;
type Change = { fontId?: string; fontVariantId?: string; fontSize?: number; color?: string; textAlign?: TextLayer['textAlign']; backgroundColor?: string | null; opacity?: number };

export const TextEditorPanel = ({ bottomInset, keyboardHeight, layer, locale, onCancel, onChangeText, onDone, onStyleChange, text }: Readonly<{ bottomInset: number; keyboardHeight: number; layer: TextLayer; locale: ProductLocale; text: string; onCancel: () => void; onChangeText: (value: string) => void; onDone: () => void; onStyleChange: (change: Change) => void }>) => {
  const [mode, setMode] = useState<Mode>('font');
  const inputRef = useRef<TextInput>(null);
  const variants = useMemo(() => getTextFontVariants(layer.fontId), [layer.fontId]);
  const updateFont = (font: TextFont) => onStyleChange({ fontId: font.groupId, fontVariantId: font.variantId });
  const retainKeyboard = (apply: () => void) => {
    apply();
    requestAnimationFrame(() => inputRef.current?.focus());
  };
  // On iOS an absolutely positioned input can mount after autoFocus ran.
  // Re-focus after layout so this editing state always requests the keyboard.
  useEffect(() => {
    const frame = requestAnimationFrame(() => inputRef.current?.focus());
    const timer = setTimeout(() => inputRef.current?.focus(), 120);
    return () => { cancelAnimationFrame(frame); clearTimeout(timer); };
  }, [layer.id]);
  return <View style={[styles.sheet, { bottom: keyboardHeight > 0 ? keyboardHeight : bottomInset }]}>
    <View style={styles.handle} />
    <View style={styles.header}><Pressable hitSlop={8} onPress={onCancel}><Text style={styles.cancel}>{t(locale, 'editor.text.cancel')}</Text></Pressable><Text style={styles.title}>{t(locale, 'editor.text.title')}</Text><Pressable hitSlop={8} onPress={onDone}><Text style={styles.done}>{t(locale, 'editor.text.done')}</Text></Pressable></View>
    <TextInput autoFocus blurOnSubmit={false} maxLength={240} multiline onChangeText={onChangeText} onLayout={() => inputRef.current?.focus()} placeholder={t(locale, 'editor.text.placeholder')} placeholderTextColor={productColor.tertiaryText} ref={inputRef} style={styles.input} value={text} />
    <View style={styles.toolRow}>{([['font', 'B', 'editor.text.font'], ['variant', 'Aa', 'editor.text.variant'], ['color', '●', 'editor.text.color'], ['size', 'A', 'editor.text.size'], ['align', '≡', 'editor.text.align'], ['background', '□', 'editor.text.background'], ['opacity', '▦', 'editor.text.opacity']] as const).map(([id, icon, label]) => <Pressable key={id} onPress={() => setMode(id)} style={styles.tool}><Text style={[styles.toolIcon, mode === id && styles.toolActive]}>{icon}</Text><Text numberOfLines={1} style={[styles.toolLabel, mode === id && styles.toolLabelActive]}>{t(locale, label)}</Text></Pressable>)}</View>
    <View style={styles.optionSlot}><Option mode={mode} layer={layer} locale={locale} variants={variants} onChange={(change) => retainKeyboard(() => onStyleChange(change))} onFont={(font) => retainKeyboard(() => updateFont(font))} /></View>
  </View>;
};

const Option = ({ layer, locale, mode, onChange, onFont, variants }: Readonly<{ layer: TextLayer; locale: ProductLocale; mode: Mode; onChange: (change: Change) => void; onFont: (font: TextFont) => void; variants: readonly TextFont[] }>) => {
  if (mode === 'font') return <ScrollView horizontal keyboardShouldPersistTaps="always" showsHorizontalScrollIndicator={false} contentContainerStyle={styles.optionRow}>{getTextFontGroups().map((font) => <FontChoice active={layer.fontId === font.groupId} font={font} key={font.groupId} onPress={() => onFont(font)} />)}</ScrollView>;
  if (mode === 'variant') return <ScrollView horizontal keyboardShouldPersistTaps="always" showsHorizontalScrollIndicator={false} contentContainerStyle={styles.optionRow}>{variants.map((font) => <FontChoice active={layer.fontVariantId === font.variantId} font={font} key={font.variantId} onPress={() => onFont(font)} />)}</ScrollView>;
  if (mode === 'color') return <ScrollView horizontal keyboardShouldPersistTaps="always" showsHorizontalScrollIndicator={false} contentContainerStyle={styles.swatchRow}>{colors.map((color) => <Pressable key={color} onPress={() => onChange({ color })} style={[styles.swatch, { backgroundColor: color }, color === '#FFFFFF' && styles.white, layer.color === color && styles.swatchActive]} />)}</ScrollView>;
  if (mode === 'size') return <ChoiceRow selected={layer.fontSize} choices={[['42', 42], ['54', 54], ['68', 68], ['88', 88], ['112', 112], ['144', 144]]} onChoose={(fontSize) => onChange({ fontSize: fontSize as number })} />;
  if (mode === 'align') return <ChoiceRow selected={layer.textAlign} choices={[[t(locale, 'editor.text.left'), 'left'], [t(locale, 'editor.text.center'), 'center'], [t(locale, 'editor.text.right'), 'right']]} onChoose={(textAlign) => onChange({ textAlign: textAlign as TextLayer['textAlign'] })} />;
  if (mode === 'background') return <ScrollView horizontal keyboardShouldPersistTaps="always" showsHorizontalScrollIndicator={false} contentContainerStyle={styles.optionRow}>{backgrounds.map((background) => <Choice active={layer.backgroundColor === background.value} key={background.label} label={t(locale, background.label)} onPress={() => onChange({ backgroundColor: background.value })} />)}</ScrollView>;
  return <ChoiceRow selected={layer.opacity} choices={[['45%', 0.45], ['70%', 0.7], ['100%', 1]]} onChoose={(opacity) => onChange({ opacity: opacity as number })} />;
};
const Choice = ({ active, label, onPress }: Readonly<{ active: boolean; label: string; onPress: () => void }>) => <Pressable onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text style={[styles.choiceLabel, active && styles.choiceLabelActive]}>{label}</Text></Pressable>;
const ChoiceRow = ({ choices, onChoose, selected }: Readonly<{ choices: readonly (readonly [string, string | number])[]; onChoose: (value: string | number) => void; selected: string | number }>) => <ScrollView horizontal keyboardShouldPersistTaps="always" showsHorizontalScrollIndicator={false} contentContainerStyle={styles.stepRow}>{choices.map(([label, value]) => <Choice active={selected === value} key={label} label={label} onPress={() => onChoose(value)} />)}</ScrollView>;
const fontPreviewAssets = {
  codystar_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/codystar_regular.png'), codystar_light: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/codystar_light.png'), gemini_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/gemini_regular.png'), kelsi_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/kelsi_regular.png'), kelsi_fill: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/kelsi_fill.png'), little_kids: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/little_kids.png'), melted_ideas: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/melted_ideas.png'), mountains_christmas_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/mountains_christmas_regular.png'), mountains_christmas_bold: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/mountains_christmas_bold.png'), sweet_dreams: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/sweet_dreams.png'), kose_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/kose_regular.png'), xinyugong_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/xinyugong_regular.png'), kurewa_gothic_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/kurewa_gothic_regular.png'), qingsong_handwriting_regular: require('../../../../miniprogram-spike/miniprogram/assets/font-previews/qingsong_handwriting_regular.png'),
} as const;
const FontChoice = ({ active, font, onPress }: Readonly<{ active: boolean; font: TextFont; onPress: () => void }>) => {
  const preview = font.variantId === 'system' ? undefined : fontPreviewAssets[font.variantId as keyof typeof fontPreviewAssets];
  return <Pressable onPress={onPress} style={[styles.fontChoice, active && styles.choiceActive]}>{preview ? <Image resizeMode="contain" source={preview} style={[styles.fontPreview, active && styles.fontPreviewActive]} /> : <Text style={[styles.choiceLabel, active && styles.choiceLabelActive]}>{font.previewText}</Text>}</Pressable>;
};

const styles = StyleSheet.create({
  sheet: { backgroundColor: productColor.surface, borderTopColor: productColor.divider, borderTopLeftRadius: 18, borderTopRightRadius: 18, borderTopWidth: StyleSheet.hairlineWidth, height: TEXT_EDITOR_PANEL_HEIGHT, left: 0, paddingHorizontal: 18, position: 'absolute', right: 0, shadowColor: productColor.ink, shadowOffset: { height: -8, width: 0 }, shadowOpacity: 0.08, shadowRadius: 22, zIndex: 12 }, handle: { alignSelf: 'center', backgroundColor: productColor.border, borderRadius: 99, height: 4, marginTop: 8, width: 36 }, header: { alignItems: 'center', flexDirection: 'row', height: 40, justifyContent: 'space-between' }, cancel: { color: productColor.secondaryText, fontSize: 14 }, done: { color: productColor.ink, fontSize: 14, fontWeight: '700' }, title: { color: productColor.ink, fontSize: 16, fontWeight: '700' }, input: { backgroundColor: '#F8F7F4', borderRadius: 10, color: productColor.ink, fontSize: 15, height: 48, paddingHorizontal: 12, paddingVertical: 11, textAlignVertical: 'top' }, optionSlot: { height: 54, overflow: 'hidden' }, optionRow: { alignItems: 'center', gap: 9, paddingVertical: 9 }, choice: { alignItems: 'center', backgroundColor: productColor.weakSurface, borderRadius: 999, height: 35, justifyContent: 'center', minWidth: 68, paddingHorizontal: 13 }, fontChoice: { alignItems: 'center', backgroundColor: productColor.weakSurface, borderRadius: 999, height: 35, justifyContent: 'center', minWidth: 82, paddingHorizontal: 13 }, fontPreview: { height: 22, tintColor: productColor.ink, width: 62 }, fontPreviewActive: { tintColor: productColor.surface }, choiceActive: { backgroundColor: productColor.ink }, choiceLabel: { color: productColor.ink, fontSize: 13, fontWeight: '600' }, choiceLabelActive: { color: productColor.surface }, swatchRow: { alignItems: 'center', gap: 16, paddingVertical: 12 }, swatch: { borderRadius: 15, height: 30, width: 30 }, white: { borderColor: productColor.border, borderWidth: StyleSheet.hairlineWidth }, swatchActive: { borderColor: productColor.ink, borderWidth: 3 }, stepRow: { alignItems: 'center', flexDirection: 'row', gap: 10, height: 54, justifyContent: 'flex-start' }, toolRow: { borderTopColor: productColor.divider, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', height: 61, justifyContent: 'space-between', paddingTop: 6 }, tool: { alignItems: 'center', flex: 1, minWidth: 0 }, toolIcon: { color: productColor.secondaryText, fontSize: 17, fontWeight: '600', height: 24, lineHeight: 22 }, toolActive: { color: productColor.ink }, toolLabel: { color: productColor.secondaryText, fontSize: 10, lineHeight: 14, textAlign: 'center' }, toolLabelActive: { color: productColor.ink, fontWeight: '700' },
});
